In [4]:
from RAFFT import rafft

In [5]:
sequence = "GGGAAACCAACCCAAAGG"
eseq, cseq = rafft.prep_sequence(sequence, 3.00, 2.00, 1.00)
# fast folding paths
#pos_list = list(range(len(sequence)))
#all_struct = rafft.bfs_pairs([[((eseq, cseq, pos_list), None, [], 0.0)]])
#all_struct.sort(key=lambda el: eval_one_struct(SEQ_COMP, el, LEN_SEQ, SEQ))

In [1]:
import subprocess
import os

In [28]:
cmd = "python RAFFT/rafft.py -s {}"
p = os.popen(cmd.format("AAAAUAAUGUACCGGACAUUCGCGCACGACCACCAUAUGGCAGAGCAUGUGUCUGUGGACCCACUAUAGCUGGGGC"))
rst = p.read().split()
print(rst[1])

...........((((((((..((...(..(((.....)))..).))..))))))).)..((((.......))))..


In [26]:
rst.split()[1]

'...........((((((((..((...(..(((.....)))..).))..))))))).)..((((.......))))..'

In [29]:
import RNA

In [34]:
RNA.param.param_file("rna_turner1999.par")

TypeError: 'property' object is not callable

In [36]:
RNA.param.__init__?

In [37]:
dir(RNA)

['ADAPTIVE',
 'ALN_DEFAULT',
 'ALN_DNA',
 'ALN_LOWERCASE',
 'ALN_RNA',
 'ALN_UPPERCASE',
 'ANY_LOOP',
 'B',
 'BONUS',
 'BRACKETS_ALPHA',
 'BRACKETS_ANG',
 'BRACKETS_ANY',
 'BRACKETS_CLY',
 'BRACKETS_DEFAULT',
 'BRACKETS_RND',
 'BRACKETS_SQR',
 'B_H',
 'CMD_PARSE_DEFAULTS',
 'CMD_PARSE_HC',
 'CMD_PARSE_SC',
 'CMD_PARSE_SD',
 'CMD_PARSE_UD',
 'CONSTRAINT_CONTEXT_ALL_LOOPS',
 'CONSTRAINT_CONTEXT_CLOSING_LOOPS',
 'CONSTRAINT_CONTEXT_ENCLOSED_LOOPS',
 'CONSTRAINT_CONTEXT_ENFORCE',
 'CONSTRAINT_CONTEXT_EXT_LOOP',
 'CONSTRAINT_CONTEXT_HP_LOOP',
 'CONSTRAINT_CONTEXT_INT_LOOP',
 'CONSTRAINT_CONTEXT_INT_LOOP_ENC',
 'CONSTRAINT_CONTEXT_MB_LOOP',
 'CONSTRAINT_CONTEXT_MB_LOOP_ENC',
 'CONSTRAINT_CONTEXT_NONE',
 'CONSTRAINT_CONTEXT_NO_REMOVE',
 'CONSTRAINT_DB',
 'CONSTRAINT_DB_ANG_BRACK',
 'CONSTRAINT_DB_DEFAULT',
 'CONSTRAINT_DB_DOT',
 'CONSTRAINT_DB_ENFORCE_BP',
 'CONSTRAINT_DB_GQUAD',
 'CONSTRAINT_DB_INTERMOL',
 'CONSTRAINT_DB_INTRAMOL',
 'CONSTRAINT_DB_PIPE',
 'CONSTRAINT_DB_RND_BRACK',
 'CONSTRA

In [41]:
RNA.read_parameter_file('rna_turner2004.par')

In [42]:
RNA.fold(sequence)

['(((.......))).....', -3.4000000953674316]

In [77]:
import numpy as np
nb_mut = np.random.uniform(1000)
nbp_indexes_to_mutate = np.where(nb_mut<0.001)

In [111]:
for i in range(1000) : 
    nb_mut = np.random.rand(76)
    nbp_indexes_to_mutate = np.where(nb_mut<0.001)
    if len(nbp_indexes_to_mutate[0])>0 : 
        print (nbp_indexes_to_mutate)

(array([67]),)
(array([15]),)
(array([12]),)
(array([32]),)
(array([49]),)
(array([45]),)
(array([41]),)
(array([67]),)
(array([27]),)
(array([16]),)
(array([44]),)
(array([37]),)
(array([27]),)
(array([72]),)
(array([26]),)
(array([ 4, 65]),)
(array([1]),)
(array([28]),)
(array([75]),)
(array([6]),)
(array([14]),)
(array([48]),)
(array([17]),)
(array([13]),)
(array([16]),)
(array([7]),)
(array([50]),)
(array([28]),)
(array([61]),)
(array([17]),)
(array([4]),)
(array([63]),)
(array([34]),)
(array([52]),)
(array([25]),)
(array([62]),)
(array([17]),)
(array([63]),)
(array([40]),)
(array([68]),)
(array([9]),)
(array([11]),)
(array([33]),)
(array([38]),)
(array([50]),)
(array([26]),)
(array([40]),)
(array([38]),)
(array([68]),)
(array([23]),)
(array([64]),)
(array([55]),)
(array([21]),)
(array([59]),)
(array([72]),)
(array([42]),)
(array([40]),)
(array([25]),)
(array([10]),)
(array([64]),)
(array([55]),)
(array([51]),)
(array([31]),)
(array([6]),)
(array([65]),)
(array([6]),)
(array([48]),

In [112]:
list(set(['A','C','G','U'])-set(['A']))

['G', 'C', 'U']

In [113]:
np.random.choice(list(set(['A','C','G','U'])-set(['A'])), 1)[0]

'C'